### ISSUE TITLE
Blog Proposal

### ISSUE THREAD

**Issue by Kshanti00** [stat231-f21/blog_data-chi-fraternity#1]
Proposal (Tuesday, Nov. 2):

Project Overview:

In order to explore more interesting data visualizations and interactivity, our group has decided to use new data rather than continuing with the police logs we used for the Shiny app. 

As we go through our senior years and see graduation on the horizon, we think it would be interesting to explore how college student outcomes are influenced by a variety of factors of the college experience. We intend to look at data from the Chronicle of Higher Education’s 2021-2022 Almanac (https://www.chronicle.com/tag/data), which presents a variety of data frames on how students, faculty, and college institutions at large have fared and how certain factors are correlated (e.g. demographics, tuition payments, financial aid packages, etc.). 

With this data, we aim to create three things: 
A Shiny simulation app that allows the user to select certain factors and see how outcomes for a student with those characteristics would statistically play out
A pair of interactive predictive models (using logistic and linear regression), one looking at the likelihood of graduation rates based on certain college student factors and another looking at predictive income levels based on certain college student factors. These predictions would use the same data as the simulation, but apply it in a different way.
A map that allows for state-by-state comparison of higher education offerings/resources. This map would allow a user to click on various states and look at data about that state’s landscape of higher education (for example, a histogram of endowments for colleges in that state, a bar chart of types of institutions in that state, average admission and enrollment rates over time in that state, etc.)

Intended Final Products:

Shiny App Simulation: 
Question: How do certain factors of a college experience affect student outcomes? In other words, how will certain traits of a college student statistically affect their post-grad outcomes?

Factors of the student (i.e. the user’s selection choices)
Demographic
Major
SAT/ACT scores (requirement, median scores)
Average financial aid package
Institution or state
Outcomes of the student (i.e. the product generated based on the user’s choices)
Graduation rate
Median student debt
Post-graduation income (within first 5 years)
Post-graduation professional fields
Grad school vs. workforce (within first 5 years)

Prediction models: 
Question: What is the likelihood of graduating based on certain factors? What is the predicted income of a college student based on certain factors?

Graduation rate: Logistic regression model
Predicted income: Linear regression model

Map: 
Question: What does the landscape of higher education look like state-by-state? (e.g. differences in resources, types of higher education offered, etc.)

Plots of college data state-by-state
Histogram (quantitative): Endowments by college in that state 
Bar chart (categorical): Type of institutions (e.g. 4-year, public, private, 2-year)
Bar chart (categorical): Areas of study
Interactive bar chart (categorical): Demographics of student, faculty, staff, administration 
Line graph (quantitative): Admission/enrollment rates over time

Timeline:

Nov. 2: Idea is decided/initial proposal is submitted
Nov. 4: All data is located, wrangled and ready to use
Nov. 9: First progress update is submitted
Nov. 12: Simulation (i.e. first visualization) is coded by this date
Nov. 15: Prediction models are done by this date
Nov. 16: Second progress update is submitted 
Nov. 19: Map (i.e. second visualization) is coded by this date
Nov. 23: Blog write-up is drafted by this date
Nov. 25: Full blog report is assembled by this date 
Nov. 28: Full blog report is edited by this date (i.e. final draft is done)
Nov. 29: Presentation is prepared by this date
Nov. 30: Presentation is done by this date
Dec. 5: Polishing touches (e.g. design elements, code readability, etc.) are completed by this date

**Comment by bebailey** [comment]
Sounds good as long as the data wrangling isn't too overwhelming for you all (did you find cleaner data?)

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by rpicciotto22** [comment]
**Progress So Far:** Our group has identified which parts of the project we will all be the point people for (i.e. who will take the lead on each element of the final blog). We have also located the sources that we will use for each data set we need for our respective project elements. Individually, we have begun retrieving the data from those sources (in some cases, that was an easy CSV download while others have turned into more complicated scraping processes). We have begun to wrangle and tidy the data that we have been able to retrieve. 

**Schedule Status:** At the moment, we are behind on our intended timeline. Here is our plan to get back on track:

**Updated Timeline:**
- Nov. 9: First progress update is submitted
- Nov. 12: All data is wrangled and ready to use
- Nov. 15: Prediction models are done by this date
- Nov. 16: 
- Two of four of the outcome plots of the college outcome simulation; user selection c/hoices are done by this date
- One of two regression models is done
- Outline of the map with a couple of the state-by-state plots done by this date
- Second progress update is submitted 
- Nov. 19: All three of the project elements are finalized
- Nov. 23: Blog write-up is drafted by this date
- Nov. 25: Full blog report is assembled by this date 
- Nov. 28: Full blog report is edited by this date (i.e. final draft is done)
- Nov. 29: Presentation is prepared by this date
- Nov. 30: Presentation is done by this date
- Dec. 5: Polishing touches (e.g. design elements, code readability, etc.) are completed by this date

**Why We Got Behind:** We got behind schedule due to both a combination of non-Data Science deadlines that precluded us from dedicating the time we wanted to this project, along with hitting unforeseen obstacles in the data scraping/wrangling processes.

**Comment by rpicciotto22** [comment]
**Progress So Far:** Two out of three of our visualizations will be using data from The Chronicle. That data has been scraped and is ready to be used. The visualizations we will use it for are the map (handled by Rafael) and a layer of clusterings on the map that can be selected by the user to look at different state-by-state metrics of college outcomes (the clusterings will be handled by Kalidas). If there is time, Kalidas will return to the regression/logistic models but will prioritize the data clusterings on the map since that will create a more cohesive final product. The third visualization (handled by Becca) has been modified so it will only look at graduation rates, post-grad earnings (those will likely be in the form of a standard bar graph that can be interactively selected to look at specific demographics and other degrees). In addition, Becca will try to use the post-grad fields data to create a word cloud that analyzes text based on which fields people are most likely to go into.

**Schedule Status:** Given that the vision for our final product has changed, our schedule will also change a bit. 

**Updated Timeline:**
- Nov. 16: 
  - One of two regression models is done
  - Outline of the map with a couple of the state-by-state plots done by this date
  - Second progress update is submitted 
- Nov. 19: 
  - Earnings Shiny tab is done
  - Graduation rates Shiny tab is done
  - Clustering is done
  - Map Shiny app skeleton is done
- Nov. 23: 
  - Data wrangling for career fields word cloud is done
  - Blog write-up is drafted by this date
- Nov. 26:
  - Map Shiny app is done
  - Word cloud is done
- Nov. 28: 
  - All visualizations are assembled/finalized
  - Full blog report is edited by this date (i.e. final draft is done)
- Nov. 29: Presentation is prepared/practiced
- Nov. 30: Presentation is done by this date
- Dec. 5: Polishing touches (e.g. design elements, code readability, etc.) are completed by this date

**Comment by bebailey** [comment]
I'm a little concerned that no one has pushed any commits to the repo since I created it... Are you working in a different repo? Please make sure to push all relevant files here (sooner rather than later so you can troubleshoot any conflicts).
